name: Build All
on:
  push:
    tags: ["v*"] # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Build multiple platforms
      - name: Build All
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o todo-linux-amd64 .
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o todo-windows-amd64.exe .
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o todo-darwin-arm64 .

      # Create GitHub release with binaries
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            todo-linux-amd64
            todo-windows-amd64.exe
            todo-darwin-arm64
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
